### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by IcarusWizard** [penn-pal-lab/LIV#2]
Hi, thanks for sharing the code and the model. 

I am trying to load the model by the provided example. However, I get an error of the following:

```
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1l1ufzVLxpE5BK7JY6ZnVBljVzmK5c4P3 
```

Although I can download the model manually from the browser, it is not the best option when deploying the model. Could you please check the permission setting of the model file? Or maybe host the model weight with a more accessible source, e.g. github release or Huggingface. 

Thanks in advance.

**Comment by JasonMa2016** [comment]
Hi,

Thank you for your interest in out work and suggestions! We have released the model on [HuggingFace](https://huggingface.co/jasonyma/LIV) now. `load_liv` will also use HuggingFace API to download the model if the default google drive code does not work for you.

Please let me know whether this resolves your issue. Thank you!

Best,
Jason

**Comment by IcarusWizard** [comment]
Thanks for the quick response. I try the new code, but unfortunately, the `gdown.download` will fail silently without raising an error. If I comment out the `gdown` part to use the `hf_hub_download` directly, the code runs perfectly. Thus, I would suggest to make `hf_hub_download` as the default option.

**Comment by JasonMa2016** [comment]
Fixed. Thank you for the great suggestion!
